import './globals.css'

import { Inter } from 'next/font/google'
import Providers from '@/app/providers'
import Header from '@components/Header'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type RootProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.className} bg-light-secondary dark:bg-dark-secondary`}>
        <Providers>
         <Header />


          {/* Page */}
          <main>{children}</main>

          {/* Footer */}
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
